// Generated by CoffeeScript 1.7.1
(function() {
  var twelve;

  twelve = function() {
    return 12;
  };

  twelve.negative = function() {
    return -12;
  };

  twelve.before = function() {
    return 12 - 1;
  };

  twelve.after = function() {
    return 12 + 1;
  };

  twelve.english = function() {
    return 'Twelve';
  };

  twelve.upHigh = function() {
    return '¹²';
  };

  twelve.downLow = function() {
    return '₁₂';
  };

  twelve.roman = function() {
    var r;
    r = function(num, ans) {
      if (ans === void 0) {
        ans = '';
      }
      switch (false) {
        case !(num > 10):
          return r(num - 10, ans + 'X');
        case !(num > 5):
          return r(num - 5, ans + 'V');
        case !(num > 0):
          return r(num - 1, ans + 'I');
        default:
          return ans;
      }
    };
    return r(twelve());
  };

  twelve.binary = function() {
    return twelve().toString(2);
  };

  twelve.octal = function() {
    return twelve().toString(8);
  };

  twelve.duodecimal = function() {
    return twelve().toString(12);
  };

  twelve.hex = function() {
    return twelve().toString(16);
  };

  twelve.summation = function() {
    var _i, _ref, _results;
    return (function() {
      _results = [];
      for (var _i = 1, _ref = twelve(); 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).reduce(function(x, y) {
      return x += y;
    });
  };

  twelve.factorial = function() {
    var _i, _ref, _results;
    return (function() {
      _results = [];
      for (var _i = 1, _ref = twelve(); 1 <= _ref ? _i <= _ref : _i >= _ref; 1 <= _ref ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this).reduce(function(x, y) {
      return x *= y;
    });
  };

  twelve.month = function() {
    return "" + (12 / 12) + " year";
  };

  twelve.element = function() {
    return 'Mg';
  };

  twelve.asteroid = function() {
    return 'Victoria';
  };

  twelve.tarot = function() {
    return 'The Hanged Man';
  };

  twelve.tarot.user = function() {
    return 'J Guile';
  };

  twelve.hexagram = function() {
    return '天地否';
  };

  twelve.quran = {};

  twelve.quran.sura = function() {
    return 'يوسف';
  };

  twelve.zodiac = function() {
    return ['Aries', 'Taurus', 'Gemini', 'Cancer', 'Leo', 'Virgo', 'Scorpio', 'Sagittarius', 'Capricorn', 'Aquarius', 'Pisces'];
  };

  twelve.astrologicalSign = function() {
    return ['Mars', 'Venus', 'Mercury', 'Moon', 'Sun', 'Mercury', 'Pluto', 'Jupiter', 'Saturn', 'Uranus', 'Neptune'];
  };

  twelve.earthlyBranches = function() {
    return ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];
  };

  twelve.chromaticScale = function() {
    return ['C', 'C♯', 'D', 'E♭', 'E', 'F', 'F♯', 'G', 'A♭', 'A', 'B♭', 'B'];
  };

  twelve['十二天'] = function() {
    return ['帝釈天', '火天', '焔魔天', '羅刹天', '水天', '風天', '毘沙門天', '伊舎那天', '梵天', '地天', '日天', '月天'];
  };

  twelve['十二直'] = function() {
    return ['建', '除', '満', '平', '定', '執', '破', '危', '成', '納', '開', '閉'];
  };

  twelve.nidanas = function() {
    return ['無明', '行', '識', '名色', '六処', '触', '受', '愛', '取', '有', '生', '老死'];
  };

  twelve.apostles = function() {
    return ['Andrew', 'Bartholomew', 'James of Alphaeus', 'James of Zebedee', 'John', 'Judas Iscariot', 'Jude Thaddeus', 'Matthew', 'Matthias', 'Philip', 'Simon Oeter', 'Simon the Zealot', 'Thomas'];
  };

  twelve.heavenlyGenerals = function() {
    return ['金毘羅', '伐折羅', '迷企羅', '安底羅', '頞儞羅', '珊底羅', '因達羅', '波夷羅', '摩虎羅', '真達羅', '招杜羅', '毘羯羅'];
  };

  twelve.olympians = function() {
    return ['Zeus', 'Hera', 'Poseidon', 'Demeter', 'Athena', 'Apollo', 'Artemis', 'Ares', 'Aphrodite', 'Hephaestus', 'Hermes', 'Hestia', 'Dionysus'];
  };

  if (typeof module !== void 0 && module.exports) {
    module.exports = twelve;
  } else if (typeof window !== "undefined" && window !== null) {
    window.twelve = twelve;
  }

}).call(this);
