// Generated by CoffeeScript 1.7.1
(function() {
  var twelve;

  twelve = function() {
    return 12;
  };

  twelve.before = function() {
    return 12 - 1;
  };

  twelve.after = function() {
    return 12 + 1;
  };

  module.exports = twelve;

}).call(this);
